export interface TabledateItem {
    companyFullName: string,
    companyId: number,
    companyIndustry: string,
    companyName: string,
    companyRegisterAddr: string,
    lastLoginTime: string,
    registerTime: string,
    vipLevel: number | string,
    index?: number,
}

export interface CompanyDetail {
    companyAddr: string,
    companyContactEmail: string,
    companyContactName: string,
    companyContactPhone: string,
    companyFullName: string,
    companyId: number,
    companyIndustry: string,
    companyIntroducation: string,
    companyLicenseUrl: string,
    companyLogoUrl: string,
    companyName: string,
    companyNature: string,
    companyOnlyWishSchool: boolean,
    companyRegisterAddr: string,
    companySize: string,
    companySocialCreditCode: string,
    companyStatus: string,
    companyTag: string,
    companyWebUrl: string,
    companyWishSchool: number[],
    companyWishSchool1: string,
    invitationTalentCount: number,
    isVip: boolean,
    newResumeCount: number,
    onlinePositionCount: number,
    refreshPositionCardCount: number,
    refreshPositionCount: number,
    resumeCount: number,
    sevenRefreshPositionCount: number,
    smsInvitationCount: number,
    userId: number,
    vipLevel:string,
}

export interface ModifyStatus{
    statusId:number,
    companyId:number
}